### ISSUE TITLE
List not unchecking items properly.

### ISSUE THREAD

**Issue by DylanLyon** [Ny0n/Nys_ToDoList#12]
For some reason this addon doesn't uncheck daily items properly. I can have everything checked in my daily list, reset will roll over, and only half of them will uncheck themselves. It seems quite random actually. Makes it very difficult to use this addon because it makes it hard to track what I've done each day.

**Comment by Ny0n** [comment]
Hey, I'm sorry to hear about that, are you sure you are in the "Daily" tab and not creating some of your items in the "All" tab by mistake? also, could you give me the addon version you are currently using please ?

**Comment by DylanLyon** [comment]
Ugh I'm just stupid you nailed it, I was making them in the All tab not thinking it made a difference. When I actually go to the Daily tab it only shows a handful of my daily tasks (which I think are the only ones resetting properly). I should be able to add the rest to the proper daily tab and I'm sure it will work.

Thanks so much for the quick response and sorry for the trouble! Definitely a user error lol.
