### ISSUE TITLE
Feature Request: Hide completed tasks/empty categories

### ISSUE THREAD

**Issue by Rauvagol** [Ny0n/Nys_ToDoList#23]
It would be nice to have the option that when a task is marked complete, it is hidden from the view, only reappearing after it resets to incomplete, Ideally when all tasks in a category are complete, the category name would also hide itself.

**Comment by Ny0n** [comment]
Yo! these options already exist, they're located in the addon options > tabs and you can configure this for each tab

**Comment by Rauvagol** [comment]
Ayy, so there is, also love the per-tab setting, so when my brain goes "wait.... did I do that? or just not add it?" its easy to check

thanks for thehelp
