### ISSUE TITLE
Feature Request: Category Nesting

### ISSUE THREAD

**Issue by Goten87** [Ny0n/Nys_ToDoList#24]
i wish we could nest Catagory's in one a other
i want to make a Daily crafring todo (for all my chars) and i wanted to make it 

```
-Dragonflight
--Crafting
---Checkbox List
--OtherCatogory
---Checkbox List
```
hope this makes a little sense dont know how to explain it realy good

**Comment by Ny0n** [comment]
Yo! This feature is already in development ("sub-categories"), I just need some more time to finish it 😉

**Comment by Ny0n** [comment]
Closing: Added in 7.3
