### ISSUE TITLE
Feature request - Add symbol in cat name

### ISSUE THREAD

**Issue by KatyPurry** [Ny0n/Nys_ToDoList#28]
Hello,

Is it possible to add these symbols in categorie name ? 

![1791841567970110](https://github.com/Ny0n/Nys_ToDoList/assets/89610869/a99897c4-7eaa-4715-a9a3-1ff21d8a9e4c)

Thank you !

**Comment by Ny0n** [comment]
Hey! I just released an update that adds this feature

To add these symbols in any name, you would need to copy and modify the following link:

|T***Interface/TargetingFrame/UI-RaidTargetingIcon_8***:***12***:***12***::::::::|t

This is called a hyperlink. When used in WoW it will automatically transform to the specified symbol.

Specifically, this link will look for the symbol in the files located at ***Interface/TargetingFrame/UI-RaidTargetingIcon_8***, which is the skull one (you can find all the other icons at this [repo](https://github.com/Gethe/wow-ui-textures/tree/live), simply change the path to target a different icon).
Also, the ***12*** represents the size in pixels, so the first is the width and the second is the height.

**Comment by Zazou89** [comment]
Awesome thankt you very much for the explanation !

**Comment by KatyPurry** [comment]
Awesome ! Thank you very much for the explanation ! I'll update addon asap !
