### ISSUE TITLE
[BUG] Can't add new entries

### ISSUE THREAD

**Issue by Garltok** [Ny0n/Nys_ToDoList#29]
On some of my characters I can't add new entries (see Pic). 

I disable all addons and still have the same problem while the other characters can have all addons enabled and still make new entries without any issues,

I also cleared the cache and reinstalled the addon, which didn't fix it.
![Screenshot 2024-02-21 062520](https://github.com/Ny0n/Nys_ToDoList/assets/41690511/2b486dd9-7f6d-4345-bd1b-dc93e22bc7f0)

**Comment by Ny0n** [comment]
Hi, I'd say that this is due to an addon conflict, but now I don't know.

Can you tell me if when that happens, you also can't add new categories ? or if an error pops up ?

You could also send me your saved variables file (Nys_ToDoList.lua file) so that I can test it myself if that's ok for you

**Comment by Garltok** [comment]
Also not sure what changed, but the problem has seemed to have fixed itself

**Comment by Ny0n** [comment]
Well I'm glad to hear this, because I really didn't know how to fix this, and I couldn't replicate it ^^
Let's hope it doesn't come back 😉

**Comment by Murplyy** [comment]
Hey, just wanted to say same issue here. Not the first time it has happened, and it usually goes away on its own.. however, no clue what causes it or why. One second I'm adding global tabs and everything is fine, the next I get the same issue where adding a tab shows it as blank (adding categories is fine, it's adding items that is messed up).

**Comment by Ny0n** [comment]
Well that's a problem. I'll have a look at it again hoping I can recreate this bug on my own. How long ago was it since the first time this happened for you ? Did it happen after creating an entry or just logging in randomly ?

**Comment by Ny0n** [comment]
ok wait I have a lead

**Comment by Ny0n** [comment]
Even better, please install this modified addon version and tell me if it continues to happen, I may have found a fix

[Nys_ToDoList-7.2-2-g5fc112e.zip](https://github.com/Ny0n/Nys_ToDoList/files/14434795/Nys_ToDoList-7.2-2-g5fc112e.zip)

**Comment by Murplyy** [comment]
> Even better, please install this modified addon version and tell me if it still happens, I may have found a fix.
> 
> [Nys_ToDoList-7.2-2-g5fc112e.zip](https://github.com/Ny0n/Nys_ToDoList/files/14434795/Nys_ToDoList-7.2-2-g5fc112e.zip)

Will do! And to answer your previous question, I am estimating to say that the first time the issue occurred for me was about 2-3 weeks ago? Anyways, I have no idea what causes the bug to occur, so I will add your modified version and see if that stops it (unless it would be more helpful to maintain the original and wait for the bug to potentially happen again, and send you that file?)

**Comment by Ny0n** [comment]
> > Even better, please install this modified addon version and tell me if it still happens, I may have found a fix.
> 
> > 
> 
> > [Nys_ToDoList-7.2-2-g5fc112e.zip](https://github.com/Ny0n/Nys_ToDoList/files/14434795/Nys_ToDoList-7.2-2-g5fc112e.zip)
> 
> 
> 
> Will do! And to answer your previous question, I am estimating to say that the first time the issue occurred for me was about 2-3 weeks ago? Anyways, I have no idea what causes the bug to occur, so I will add your modified version and see if that stops it (unless it would be more helpful to maintain the original and wait for the bug to potentially happen again, and send you that file?)

For now playing with the modified version is still the best thing, I'll probably update the addon soon with that change, and if it still happens then at least I know that it's due to something else. Thanks for the reply!
