### ISSUE TITLE
[Feature Request] An additional tab for "scratchpad" or "notepad"?

### ISSUE THREAD

**Issue by radhaz** [Ny0n/Nys_ToDoList#30]
Would it be possible to get one more tab that allows players to jot down quick notes independent of the weekly/daily tabs? 

This would be useful for making lists of things we're keeping an eye out for or notes on how to do particular things (like boss order in legacy dungeons or locations for things etc)

**Comment by Ny0n** [comment]
Hey, I'm sorry this isn't planned at the moment. If you want you can sort of do this by adding descriptions on elements, they can allow you to write pretty much anything you want, and you can treat the name of the item as the title. So you could for example create a new tab, and everything that's in it will be your notepad through the items descriptions.

**Comment by radhaz** [comment]
> Hey, I'm sorry this isn't planned at the moment.

Thanks for the response, I'll close the post since it's not happening
