### ISSUE TITLE
NA weekly reset support

### ISSUE THREAD

**Issue by icbat** [Ny0n/Nys_ToDoList#33]
I noticed that my weeklies didn't reset on Tuesday like I expected; from glancing at the code it looks like it's always resetting weeklies on EU-time aka Wednesday.

You might be able to fork behavior based on the region (available via [GetCurrentRegion](https://wowpedia.fandom.com/wiki/API_GetCurrentRegion)) or you could potentially do some more complicated math if you prefer using [C_DateAndTime.GetSecondsUntilWeeklyReset()](https://wowpedia.fandom.com/wiki/API_C_DateAndTime.GetSecondsUntilWeeklyReset).

I'm happy to try to make a PR if that would help! Thanks for the lovely addon, it really solves a lot of my needs!

**Comment by Ny0n** [comment]
Hello, you're right, the addon is setup on EU time by default, though you can edit the weekly reset day through the in-game options, so I never really updated the code.

Thanks for the suggestions, considering that you're not the first one to tell me this, I'll probably fix this in the code for the next update 😉

**Comment by icbat** [comment]
Thanks for taking a look! I actually can't find it on the options for the addon, though maybe I'm just missing it. Thank you either way!

**Comment by Ny0n** [comment]
It's configured for each tab, so in the addon options > tabs > any tab > auto-reset

**Comment by icbat** [comment]
Aha, I did not know I could click into the tab options! Thank you!
