### ISSUE TITLE
[Classic] v5.5.1 tdlButton:SetPoint() error

### ISSUE THREAD

**Issue by Road-block** [Ny0n/Nys_ToDoList#4]
Probably best to do this here than in comments 😄 

Full errorstack is
```
3x ...nterface\Nys_ToDoList\Data\optionsManager.lua:133: tdlButton:SetPoint(): Wrong object type for function
[C]:: in function 'SetPoint'
...nterface\Nys_ToDoList\Data\optionsManager.lua:133: in function 'RefreshTDLButton'
...nterface\Nys_ToDoList\Data\optionsManager.lua:127: in function 'CreateTDLButton'
Nys_ToDoList\Data\init.lua:190: in function <Nys_ToDoList\Data\init.lua:136>
[C]:: ?
```
Saved variables for the affected character [here](https://gist.github.com/Road-block/713bc15ae26b3c1f4707f679551c5134).

I'm guessing if you load that profile you should be able to reproduce it.

**Comment by Ny0n** [comment]
Yup, good thought x)
okay let me test this profile

**Comment by Road-block** [comment]
The only addon I can find in my AddOns folder implementing a fadeInfo.fadeTimer is [Immersion](https://www.curseforge.com/wow/addons/immersion).

It's implementing a fader for frames in its \Display\Animation.lua file.  

Now how it managed to corrupt NysToDo saved variables I have no clue (yet).

**Comment by Ny0n** [comment]
well yea, if we delete the tdlButton key it corrects the prb for me, did you check that? like does deleting the tdlbutton key in the saved variable solves the prb or does it gets recorrupted?

**Comment by Ny0n** [comment]
but apart from that yea, it must be an other addon or i have no clue, i'll try installing immersion

**Comment by Road-block** [comment]
So yeah running
```lua
/run NysTDL.db.profile.tdlButton=nil;ReloadUI()
```
in game gets rid of the error and in subsequent reloads remains fine.

I guess we can file this under life's great mysteries.

**Comment by Ny0n** [comment]
okay, well i guess i'll add a one time reset of this value and the frame's pos too for the update :)
Thank you for helping btw!

**Comment by Road-block** [comment]
Thanks for the nice addon and apologies for the false alarm.  
I've no idea how that got into the saved variables.  
I didn't even have the button enabled in the options.
