### ISSUE TITLE
Renaming an entry left the old one duplicated behind

### ISSUE THREAD

**Issue by cremor** [Ny0n/Nys_ToDoList#6]
I'm not 100% how I managed to do this, but I somehow duplicated an entry by renaming it. I think I renamed it in the "all" tab and there it was shown correctly afterwards. But on the "daily" tab (the item I renamed was a daily one) it still showed up with the old name and didn't synchronize the checked state with the renamed entry.

I had to delete both entries and recreate it to resolve the issue.

**Comment by Ny0n** [comment]
Okay so while trying to reproduce this bug, i've just found out that if we rename a daily or weekly item while we're in the all tab, it deletes the item from the daily or weekly tab, transforming it into an only 'all' tab item, sooooo thanks :D 
The thing is that i wasn't able to reproduce the dublicate bug, may i ask what the item name was before/after, if it was a favorite or had a description? it might help me to recreate the bug

**Comment by cremor** [comment]
I think the old name was "2 Maw Dailies" and the new was "2/3 Maw Dailies" or maybe just "Maw Dailies".
I was not a favorite and didn't have a description. But it might have already been checked.

**Comment by Ny0n** [comment]
hmm okay thanks, i'll try to look into it further.
but at least i caught the other one, maybe it was linked, we'll see =p
