### ISSUE TITLE
Enhancement Request: Hide Checked Items should apply to "All" Tab.

### ISSUE THREAD

**Issue by karpana** [Ny0n/Nys_ToDoList#8]
When the Hide Checked Items option is selected for Daily and Weekly tasks, they don't "hide" from the "All tab".

**Comment by Ny0n** [comment]
Ooh true, thanks for telling me 👍

**Comment by karpana** [comment]
maybe there's a way to push them to the bottom instead of outright hiding them?
the problem I'm having is that I use the daily/weekly tabs to create my ttasks...
but "manage them" in the "all" tab.  Meaning all of the completed tasks clutter up my to do list.
